### PR TITLE
removed duplicates

### PR DESCRIPTION
**Pull request by agron2017**

### CODE REVIEW

**Review by agron2017 — COMMENTED** [review]
good

**Comment by h4ck3rm1k3** [comment]
flm, how you doing agron? we moved to NJ. Lets meet up some time.

**Comment by agron2017** [comment]
Hey Mike,

nice to hear from you. Welcome back to NJ. I live in Ridgefield and work in
Edison. Which are you closer to?

BTW, I imported all flossk github projects to gitlab.
https://gitlab.com/flosskies. We just need to update the readme.md on
github to let people know we're now in gitlab.

Thanks,
//Agron

**Comment by h4ck3rm1k3** [comment]
we are in trenton so edison is closer, we can meet in the middle, new brunswick?

**Comment by agron2017** [comment]
Awesome. I can come tomorrow to New Brunswick at noon which doesnt leave us
much time, or after work, around 5 or 6.

**Comment by h4ck3rm1k3** [comment]
I cannot meet tomorrow, and we should take this offline. Lets get together soon.

**Pull request merged**
